services:
#    device_keeper.example:
#        class: DeviceKeeperBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    device_keeper.basic_authentication.success.listener:
        class: DeviceKeeperBundle\EventListener\BasicAuthenticationDefaultPasswordListener
        arguments: ["almostemptypassword"]
        tags:
#            - { name: kernel.event_listener, event: security.authentication.success , method: OnSecurityAuthenticationSuccess}
            - { name: kernel.event_listener, event: security.authentication.success}

    device_keeper.basic_authentication.failure.listener:
        class: DeviceKeeperBundle\EventListener\BasicAuthenticationDefaultPasswordListener
        arguments: ["almostemptypassword"]
        tags:
#            - { name: kernel.event_listener, event: security.authentication.failure , method: OnSecurityAuthenticationFailure}
            - { name: kernel.event_listener, event: security.authentication.failure}


# Doctrine Configuration
doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            house_keeper_devicekeeper_data_mysql:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: house_keeper_telemetry_data_mysql_conn
                mappings:
                    DeviceKeeperBundle:
                        type: annotation           