<?php

namespace SoftDeviceActorBundle\Repository;

/**
 * TBSoftDevicesTokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TBSoftDevicesTokensRepository extends \Doctrine\ORM\EntityRepository
{
}
