<?php

namespace TBStatBundle\Repository\MySQL;

/**
 * TBTelemetryInvoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TBTelemetryInvoicesRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    
}
