<?php

namespace DeviceKeeperBundle\Repository;

/**
 * OwnerInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
