<?php

namespace DeviceKeeperBundle\Repository;

/**
 * OwnerGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
