<?php

namespace DeviceKeeperBundle\Repository;

/**
 * OwnerGroupDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerGroupDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
