<?php

namespace DeviceKeeperBundle\Repository;

/**
 * TariffDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
